[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CitableBase = "d6f014bd-995c-41bd-9893-703339864534"
CitableObject = "e2b2f5ea-1cd8-4ce8-9b2b-05dad64c2a57"
CiteEXchange = "e2e9ead3-1b6c-4e96-b95f-43e6ab899178"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
CSV = "0.10"
CitableObject = "0.15"
CiteEXchange = "0.10"
Dash = "1"
DataFrames = "1.3"
julia = "1.8"
