[deps]
CitableAnnotations = "63f90415-d3ea-41a7-8107-8cc186a9b888"
CitableBase = "d6f014bd-995c-41bd-9893-703339864534"
CitableImage = "17ccb2e5-db19-44b3-b354-4fd16d92c74e"
CitableObject = "e2b2f5ea-1cd8-4ce8-9b2b-05dad64c2a57"
CitablePhysicalText = "e38a874e-a7c2-4ff3-8dea-81ae2e5c9b07"
CitableText = "41e66566-473b-49d4-85b7-da83b66615d8"
CiteEXchange = "e2e9ead3-1b6c-4e96-b95f-43e6ab899178"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[compat]
CitableAnnotations = "0.3"
CitableBase = "10"
CitableImage = "0.6"
CitableObject = "0.15"
CitablePhysicalText = "0.9"
CitableText = "0.15"
CiteEXchange = "0.10"
Dash = "1"
julia = "1.7"
